name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
env:
  version: ${{ github.sha }}
  dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
  dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
  base_url: ${{ secrets.REACT_APP_BASE_URL }}


jobs:

  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: 
        echo hello;
        docker build . --file Dockerfile --tag phongvanngo/kconnect-signalling-server:latest --build-arg REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }};
        docker tag phongvanngo/kconnect-signalling-server:latest phongvanngo/kconnect-signalling-server:$version;
        
    - name: Push Docker Image
      run:
        echo hello;
        docker login --username=${dockerhub_username} --password=${dockerhub_password};
        docker push phongvanngo/kconnect-signalling-server:$version;
        docker push phongvanngo/kconnect-signalling-server:latest;
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: 
          docker pull phongvanngo/kconnect-signalling-server; 
          docker stop kconnect-signalling-server; 
          docker rm kconnect-signalling-server; 
          docker run 
            -d 
            --name kconnect-signalling-server  
            -p 123456:8999
            phongvanngo/kconnect-signalling-server:latest;
            docker image prune --filter="dangling=true"  -f;
        
